### ISSUE TITLE
Heroku: remove VCS committed generated code if possible

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma2-e2e-tests#101]
We currently commit generated on Heroku:

https://github.com/prisma/prisma2-e2e-tests/tree/master/platforms/heroku/prisma/prisma-client-js

@divyenduz I'd like to undo this in the future if possible. If it's not possible, please write here why.

**Comment by divyenduz** [comment]
This is why https://github.com/prisma/prisma2/issues/1540

**Comment by divyenduz** [comment]
In an unrelated setup, Heroku + Prisma client just worked without VCS https://github.com/divyendu-test/p2-bouncer
