### ISSUE TITLE
Stream error logs

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2-e2e-tests#12]
On errors in Heroku/Now etc, the errors needs to be manually looked up, this can be fixed by streaming logs as a step (maybe all the time?) to get a first view into platform failures.

**Comment by divyenduz** [comment]
This applies to all platforms, whenever you are working on a new platform do it. We will add this to existing platforms soon.

**Comment by divyenduz** [comment]
Done for heroku and now via https://github.com/prisma/prisma2-e2e-tests/pull/17
I stream logs on test failure

**Comment by steebchen** [comment]
Lambda via https://github.com/prisma/prisma2-e2e-tests/pull/18

**Comment by steebchen** [comment]
@divyenduz remember #17 needs to be adapted to not fail silently as discussed

**Comment by divyenduz** [comment]
Yes, on my list for today (maybe in an hour or so). I will just always stream logs.

**Comment by steebchen** [comment]
Yep, starting now we will stream logs by default. And no hurry, just wasn't sure if you "have it on your list" already :)

**Comment by divyenduz** [comment]
Done via https://github.com/prisma/prisma2-e2e-tests/pull/19

**Comment by divyenduz** [comment]
Figuring out if this is possible for CSB.

**Comment by steebchen** [comment]
GCP done via #24

**Comment by divyenduz** [comment]
Wherever streaming logs was possible from my end is done. Rest are open conversations. 

Feel free to close this issue @steebchen once you feel the same.

**Comment by steebchen** [comment]
Just FYI, azure logs are not streamed due to long delays
