### ISSUE TITLE
Add a "how to run this locally" section to all readmes

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma2-e2e-tests#184]
(internal note: @steebchen is taking over all tasks)

generic
- [x] basic @steebchen 

bundlers
- [x] parcel ~~@divyenduz~~ @steebchen
- [x] rollup ~~@divyenduz~~ @steebchen
- [x] webpack ~~@divyenduz~~ @steebchen

frameworks
- [x] nestjs @steebchen 
- [x] nextjs @steebchen 
- [x] nexus @steebchen 

packagers
- [x] npm @steebchen 
- [x] yarn @steebchen 
- [x] yarn workspaces @steebchen 

databases
- [x] digitalocean-pgbouncer @divyenduz 
- [x] docker-pgbouncer @divyenduz 

platforms
- [x] azure-functions-linux @steebchen
- [x] lambda @steebchen
- [x] azure-functions-windows @steebchen
- [x] firebase-functions @steebchen
- [x] gcp-functions @steebchen
- [x] serverless-lambda @steebchen
- [x] netlify @divyenduz
- [x] codesandbox @divyenduz
- [x] netlify-ci-build @divyenduz
- [x] netlify-zisi @divyenduz
- [x] heroku @divyenduz
- [x] zeit-now @divyenduz

libraries
irrelevant, since they will be moved to examples soon

**Comment by janpio** [comment]
Everything is checked here, can this be closed now?
