### ISSUE TITLE
Rename Photon to Prisma Client

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma2-e2e-tests#23]

**Comment by steebchen** [comment]
Already done via #9. Or did you find any specific mentions of photon which should be migrated?

**Comment by Jolg42** [comment]
In the READMEs and `prisma.schema` we did this renaming, it is purely cosmetic: 
```diff
- generator photon {
+ generator client {
	provider = "prisma-client-js"
}
```

Also there is one PhotonJS mention here https://github.com/prisma/prisma2-e2e-tests/blob/d1f462864e6fa2828d230afd11a7bc3cc0c11f2b/README.md#L3 that could be renamed to "Prisma Client JS" (with a link maybe? -> https://github.com/prisma/prisma-client-js)

Also the links `https://github.com/prisma/prisma2/blob/master/docs/photon/api.md` are broken, use `https://github.com/prisma/prisma2/blob/master/docs/prisma-client-js/api.md`

There are also some `Lift` left that could be renamed to `Prisma Migrate` / `prisma2 migrate` https://github.com/prisma/prisma2-e2e-tests/search?q=lift&unscoped_q=lift
