### ISSUE TITLE
Add output of version(s) to all CI runs

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-e2e-tests#244]
It would make it much easier _what_ exactly is being tested, e.g. https://github.com/prisma/prisma2-e2e-tests/runs/539438650?check_suite_focus=true

Best just an additional step "output versions" that outputs `--version`, maybe also the `@prisma/cli` and `@prisma/client` version from `package.json` directly. also node and npm maybe.

**Comment by steebchen** [comment]
Is it okay if that output goes into the same step as the rest runs in the first few lines (maybe with some `------------` separators)? Otherwise, we need to add it to each individual job, and thus may be easily forogotten.

**Comment by janpio** [comment]
Yes.
