### ISSUE TITLE
Widen tested functionality (Prisma Client, schema, ...) per project

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-e2e-tests#251]
Right now each test here is testing a very limited set of functionality - it really is just checking if Prisma works at all on the framework, platform etc.

It might be worth to define a common set of functionality we want to confirm. The database should cover all the different relation types we have, the Prisma Client calls should be all the relevant ones (create, delete, update, find) in all the relevant combinations (so for different kind of relation setups etc).

The _full_ version of this of course might be to run something similar to the full Integration test suite that we use for Client itself - but for now just expanding on the existing set of simple "does it respond to a request and return the correct data" might give us more insight.

**Comment by steebchen** [comment]
IMHO, we should do the exact opposite regarding testing database functionality like relations. This reduces complexity, maintenance, and allows us to just test for what we actually want to test: if Prisma works on a given platform.

**Comment by janpio** [comment]
Ok, let's do that: Please create an issue and do the work required to close it 👍

**Comment by steebchen** [comment]
created https://github.com/prisma/prisma2-e2e-tests/issues/341
