### ISSUE TITLE
Change how test.sh is run

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-e2e-tests#252]
Right now you have to manually call `test.sh` in your `run.sh` to make sure the tests for a project are run. This can lead to that being forgotten and the tests giving you a wrong sense of security (exhibit https://github.com/prisma/prisma2-e2e-tests/pull/250 and https://github.com/prisma/prisma2-e2e-tests/pull/248)

Suggestion:

- The `test-all.sh` should be modified to not only run `run.sh`, but also a `test.sh` and `finally.sh` (This would also enable us to output a separator before running these scripts, making the log output in CI much easier to read, see https://github.com/prisma/prisma2-e2e-tests/pull/249)
- `finally.sh` would enable us to do things that are currently doing after manually executing `test.sh` like getting logs, cleaning up the project and so on.
- This would also mean that projects using `yarn test` instead of `test.sh` need to add a empty `test.sh`, optionally with a comment pointing out or echoing how the tests are run in that project.

**Comment by steebchen** [comment]
Simple suggestion: We force every project to create a `test.sh`, so if you use `yarn test` you just put that command into `test.sh`.

**Comment by steebchen** [comment]
One obstacle: some projects provide parameters to test.sh. Need to find a workaround for that, since you can't reference variables to a parent shell, so probably the best bet is to save state in temp files...
