### ISSUE TITLE
netlify-ci-build: Expects wrong version

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-e2e-tests#258]
See this test run: https://github.com/prisma/prisma2-e2e-tests/pull/255/checks?check_run_id=543565762

In the logs you can see the following:
```
expected '***"version":"2.0.0-alpha.982","createUser":***"id":"12345","email":"alice@prisma.io","name":"Alice"***,"updateUser":***"id":"12345","email":"bob@prisma.io","name":"Bob"***,"users":***"id":"12345","email":"bob@prisma.io","name":"Bob"***,"deleteManyUsers":***"count":1***', got '***"version":"2.0.0-alpha.983","createUser":***"id":"12345","email":"alice@prisma.io","name":"Alice"***,"updateUser":***"id":"12345","email":"bob@prisma.io","name":"Bob"***,"users":***"id":"12345","email":"bob@prisma.io","name":"Bob"***,"deleteManyUsers":***"count":1***'
```

The difference here is the `version`: `2.0.0-alpha.982` vs. `2.0.0-alpha.983` - and 982 is expected because that is what the dependency is pinned to.

How can it be that it expects a different Client version from `prisma-version.txt` than what it is pinned to?

**Comment by janpio** [comment]
Possibly related because happened around that time: https://github.com/prisma/prisma2-e2e-tests/commit/7884304bbddc88a4c4ff6f898702344382d62040 If this is the reason, it would make all these tests flaky when a new version is published during the test run. (But how should this even influence the test run!?)

**Comment by steebchen** [comment]
@divyenduz

**Comment by divyenduz** [comment]
This is resolved with the recent netlify platform improvements.
