### ISSUE TITLE
Bundlers

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2-e2e-tests#31]
- [x] Webpack via https://github.com/prisma/prisma2-e2e-tests/pull/30
- [x] Parcel via https://github.com/prisma/prisma2-e2e-tests/pull/32
- [x] Rollup https://github.com/prisma/prisma2-e2e-tests/pull/34
- (not yet: Browserify with `--node`)

Reference: 
https://www.notion.so/prismaio/Important-Frameworks-Libraries-for-Prisma-3a95356a70f342f2ae999451bbd2d1fe#813eaba7398c4c7b9027fd79de913482

**Comment by steebchen** [comment]
added browserify to the list

**Comment by steebchen** [comment]
(browserify was marked as "not yet" internally, so I'll close this again until we really want to add it)
