### ISSUE TITLE
Make sure correct version is tested?

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-e2e-tests#51]
Do all these tests somehow make sure the deployment is actually using the current Prisma version? Or do they when they succeeded once, then do not crash on deployment, but still return the old stuff, still pass?

**Comment by janpio** [comment]
2 solutions:

1. either check for the version somehow
2. on build somehow create a random number that will later be returned by the endpoint to be checked

(second one makes sure the correct build is deployed)

**Comment by divyenduz** [comment]
A soft way to test correct version that is already in place, is early failure of the CI. In case anything goes wrong, the build fails instantly. 

But to ensure this, apart from 1,2 suggested by Jan, we can also,

3. Programmatically remove the deploy after each test, to retain the URL and ensure it is a new deploy in each build.

**Comment by janpio** [comment]
Removing the deploy would make it impossible to debug or reproduce stuff that happened during CI, right? Maybe removing it before the next run though.

**Comment by steebchen** [comment]
As long as we can stream the logs in CI, we can remove it (for example, I create new deployments from scratch each time with GCP, because otherwise you'll get conflicts). If we're not able to stream logs, then we should not delete the deployment.

**Comment by steebchen** [comment]
We could dynamically replace a placeholder `__REVISION__` in an index.ts file, and compare if the deployment reports the same version to make sure the correct deployment was tested. We can also use the git hash there, it doesn't have to be the Prisma version. It's ugly, but I currently can't think of a better approach. Any other suggestions?

**Comment by janpio** [comment]
Hm, maybe I am misunderstanding something:

1. The test script running knows which version it should be testing, as it upgraded to that just now, right? 
2. And the script we are testing can just read the version in `package.json` of the `prisma` dependency, right? 
3. Then just compare the two - and you know if the correct version is being tested.

**Comment by steebchen** [comment]
1) Yes.
2) No, because the script which is uploaded in the cloud is usually just a single index.js file, so it doesn't have a package.json to read.

**Comment by janpio** [comment]
Ah right, so this would have to happen in `generate` so that it can be read from the generated Client for example? Wouldn't that make sense anyway as a comment at the beginning of the `index.js` or similar?

**Comment by steebchen** [comment]
Yes, that's what I'm suggesting (the `__REVISION__` replace thing).

**Comment by janpio** [comment]
Ah right, so this would have to happen in `generate` so that it can be read from the generated Client for example? Wouldn't that make sense anyway as a comment at the beginning of the `index.js` or similar?

**Comment by steebchen** [comment]
I'm not sure what you mean by `generate`, this would just go into our own script on "generation time" to make sure deployments don't mismatch; in this case it wouldn't have to do anything with Prisma. We don't really want to verify if the generated prisma client version is the same as we defined in package.json, since we can expect that because we use a package manager.

**Comment by janpio** [comment]
I meant:
When you run `prisma2 generate` it could put the version of the CLI and client generator used to generate the Prisma Client in a comment that you then would be able to read.

**Comment by steebchen** [comment]
It could, but I would need it as an exported variable. A comment would not help much.

**Comment by janpio** [comment]
Ok, same effort though and could be useful for other debugging as well? Then we should create an issue.

**Comment by steebchen** [comment]
I'm not sure, I couldn't think of any use case where you'd need the Prisma version...

**Comment by steebchen** [comment]
I created https://github.com/prisma/prisma2/issues/1741 anyway, because it saves the e2e repo a lot of trouble and the comment like you said could also prevent trouble if user want to verify that their generated code is not outdated.
