### ISSUE TITLE
Readmes

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2-e2e-tests#52]
With the following TOC (WIP), Divy, Luca will discuss a format and apply it to all test items. 

```
Introduction: What are we testing and any details of it

Deployment: Anything specific about this deployment? 

Friction points: Links to issues on how a platform/test/integration can be improved
```

**Comment by janpio** [comment]
If "Friction Points" also includes all the "unexpected" changes that were needed on the project itself, I think this would be good. Please make sure all the folder follow the same template so it is really easy to follow.

**Comment by janpio** [comment]
Left some comments on the diff of https://github.com/prisma/prisma2-e2e-tests/pull/55/files

**Comment by steebchen** [comment]
https://github.com/prisma/prisma2-e2e-tests/pull/148
