### ISSUE TITLE
Make some platforms more robust

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma2-e2e-tests#62]
Some platforms are failing intermittently. We should fix that to make the tests more robust and thus save time in the future.

The following collection lists all platforms which are often failing, along with an example test run which is verified to be a false negative.

Platforms (sorted by failing count; starting with the platform which fails most frequently):
- [x] ⚠️ (failing very often) netlify-ci-build @divyenduz  https://github.com/prisma/prisma2-e2e-tests/runs/441080757
- [x] zeit-now @divyenduz https://github.com/prisma/prisma2-e2e-tests/runs/441281230
- [x] netlify @divyenduz https://github.com/prisma/prisma2-e2e-tests/runs/441157604
- [x] heroku @divyenduz https://github.com/prisma/prisma2-e2e-tests/pull/64/checks?check_run_id=441544640
- [ ] firebase functions @steebchen 
- [x] firebase functions (old failures) @steebchen via https://github.com/prisma/prisma2-e2e-tests/pull/88 https://github.com/prisma/prisma2-e2e-tests/pull/71/checks?check_run_id=442147398

**Comment by divyenduz** [comment]
Related to netlify: https://community.netlify.com/t/common-issue-my-site-deploy-fails-unless-netlifys-build-cache-is-cleared/3035

**Comment by divyenduz** [comment]
This is addressed with the recent changes. Please open a new issue with a fresh list of flaky platforms if we want to address new issues.
