### ISSUE TITLE
Remove temporary empty environment variables

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma2-e2e-tests#67]
This is currently blocked by https://github.com/prisma/prisma2/issues/800

- [x] GCP functions https://github.com/prisma/prisma2-e2e-tests/blob/8c4e012ac10d2eab88e85e473b59314b082f865f/platforms/gcp-functions/package.json#L5
- [x] firebase functions https://github.com/prisma/prisma2-e2e-tests/blob/8c4e012ac10d2eab88e85e473b59314b082f865f/platforms/firebase-functions/functions/package.json#L10

**Comment by janpio** [comment]
Can this be closed now that both are checked?
