### ISSUE TITLE
Slack notifications

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-e2e-tests#92]
We are running these tests quite frequently now, and what is missing is being informed about test runs and most importantly test failures.

I am pretty sure there are multiple Slack actions that can post to Slack - we should use one of them to a) send messages for all test runs (channel #feed-e2etests) and b) send messages for only the failed runs ((channel #feed-e2etests-fail).

**Comment by steebchen** [comment]
Good idea! We should send status updates from the master branch only, which we can do in a separate step and filtering by branch name.

**Comment by steebchen** [comment]
We should not implement this before https://github.com/prisma/prisma2-e2e-tests/issues/62 is fixed, otherwise we'll get too many false negatives.

**Comment by janpio** [comment]
Please go ahead anyway, this will be adapted from this repo into all the others ones we have using Github Actions. (You might leave it disabled or disable again if the flakyness is indeed a problem)
