### ISSUE TITLE
Use Prisma org for all platforms

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2-e2e-tests#96]
- [x] zeit is from Divy's account @divyenduz #142
- [x] heroku @divyenduz

**Comment by steebchen** [comment]
@divyenduz Can we close this?

**Comment by divyenduz** [comment]
I need to think what is deployed where. Netlify is with Prisma for sure. What about lambda etc?

**Comment by divyenduz** [comment]
Heroku is still on my account (with `singh@prisma.io` email though) afaik.

**Comment by steebchen** [comment]
From my side, everything is now using Prisma accounts. Updated the comment above to reflect heroku.

**Comment by divyenduz** [comment]
This is done!
